---

- hosts: localhost
  vars:
    jboss_home: /home/esiegl/jboss/anstest
    port_offset: 100
    jboss_version: jboss-eap-7.0.0
  tasks:
    - name: Stop JBoss in case it exists
      wildfly_configure:
        jboss_home: "{{jboss_home}}"
        jboss_version: "{{jboss_version}}"
        jboss_port_offset: "{{port_offset}}"
        stop: true
      ignore_errors: yes
    - name: delete jboss home
      file: path="{{jboss_home}}" state=absent
    - name: Unzip JBoss Package
      wildfly_install:
        zip: "/home/esiegl/Downloads/{{jboss_version}}.zip"
        jboss_home: "{{jboss_home}}"
    - name: Start JBoss
      wildfly_configure:
        jboss_home: "{{jboss_home}}"
        jboss_version: "{{jboss_version}}"
        jboss_port_offset: "{{port_offset}}"
        restart: true
